# Generated by Django 5.0.4 on 2026-06-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_transcription_docker_feteched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalstatementwithlevel",
            name="category",
            field=models.CharField(
                choices=[
                    ("OPENING", "Opening"),
                    ("QUESTIONING", "Questioning"),
                    ("PRESENTING", "Presenting"),
                    ("CLOSING_OUTCOME", "Closing & Outcome"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statementlevelprompt",
            name="category",
            field=models.CharField(
                choices=[
                    ("OPENING", "Opening"),
                    ("QUESTIONING", "Questioning"),
                    ("PRESENTING", "Presenting"),
                    ("CLOSING_OUTCOME", "Closing & Outcome"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
